name: Lint

on: 
  pull_request:
  push:
    branches: master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install SwiftFormat
      uses: Cyberbeni/install-swift-tool@v2
      with:
        url: https://github.com/nicklockwood/SwiftFormat
    - name: Install SwiftLint
      uses: Cyberbeni/install-swift-tool@v2
      with:
        url: https://github.com/realm/SwiftLint
    - name: Lint
      run: Scripts/lint.sh
